title: Dakota Gagne
description: Programmer / Developer
site_title: "Portfolio - Dakota Gagne"

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Stryker69669
blog_url: None
email: dakotaevan10@gmail.com
twitter_username: UNKN
# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics:
