title: Dakota Gagne
description: Full Stack Developer
site_title: "Portfolio - Dakota Gagne"

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: DakotaGagne
blog_url: None
email: dakotaevan10@gmail.com
email2: dakotaevan@hotmail.com
linkedin_username: /in/dakota-gagne
twitter_username: UNKN
# absolute or relative
profile_picture: assets/images/headshot.jpg

# Google Analytics ID
google_analytics:
